export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_DASH_BOARD_REQUEST = "GET_DASH_BOARD_REQUEST";
export const GET_DASH_BOARD_SUCCESSFUL = "GET_DASH_BOARD_SUCCESSFUL";
export const GET_DASH_BOARD_FAILED = "GET_DASH_BOARD_FAILED";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const GET_PAST_ORDERS_REQUEST = "GET_PAST_ORDERS_REQUEST";
export const GET_PAST_ORDERS_SUCCESSFUL = "GET_PAST_ORDERS_SUCCESSFUL";
export const GET_PAST_ORDERS_FAILED = "GET_PAST_ORDERS_FAILED";

export const GET_ADDRESSES_REQUEST = "GET_ADDRESSES_REQUEST";
export const GET_ADDRESSES_SUCCESSFUL = "GET_ADDRESSES_SUCCESSFUL";
export const GET_ADDRESSES_FAILED = "GET_ADDRESSES_FAILED";

export const GET_CATEGORY_ITEMS_REQUEST = "GET_CATEGORY_ITEMS_REQUEST";
export const GET_CATEGORY_ITEMS_SUCCESSFUL = "GET_CATEGORY_ITEMS_SUCCESSFUL";
export const GET_CATEGORY_ITEMS_FAILED = "GET_CATEGORY_ITEMS_FAILED";
export const SELECT_ADDRESS_FOR_DELIVERY = "SELECT_ADDRESS_FOR_DELIVERY";
