export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const GET_DASH_BOARD_REQUEST = "GET_DASH_BOARD_REQUEST";
export const GET_DASH_BOARD_SUCCESSFUL = "GET_DASH_BOARD_SUCCESSFUL";
export const GET_DASH_BOARD_FAILED = "GET_DASH_BOARD_FAILED";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const GET_PAST_ORDERS_REQUEST = "GET_PAST_ORDERS_REQUEST";
export const GET_PAST_ORDERS_SUCCESSFUL = "GET_PAST_ORDERS_SUCCESSFUL";
export const GET_PAST_ORDERS_FAILED = "GET_PAST_ORDERS_FAILED";

export const GET_ADDRESSES_REQUEST = "GET_ADDRESSES_REQUEST";
export const GET_ADDRESSES_SUCCESSFUL = "GET_ADDRESSES_SUCCESSFUL";
export const GET_ADDRESSES_FAILED = "GET_ADDRESSES_FAILED";

export const GET_CATEGORY_ITEMS_REQUEST = "GET_CATEGORY_ITEMS_REQUEST";
export const GET_CATEGORY_ITEMS_SUCCESSFUL = "GET_CATEGORY_ITEMS_SUCCESSFUL";
export const GET_CATEGORY_ITEMS_FAILED = "GET_CATEGORY_ITEMS_FAILED";
export const SELECT_ADDRESS_FOR_DELIVERY = "SELECT_ADDRESS_FOR_DELIVERY";

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESSFUL = "GET_ALL_CATEGORIES_SUCCESSFUL";
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED";

export const SAVE_NEW_ADDRESS_REQUEST = "SAVE_NEW_ADDRESS_REQUEST";
export const SAVE_NEW_ADDRESS_SUCCESSFUL = "SAVE_NEW_ADDRESS_SUCCESSFUL";
export const SAVE_NEW_ADDRESS_FAILED = "SAVE_NEW_ADDRESS_FAILED";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESSFUL = "UPDATE_ADDRESS_SUCCESSFUL";
export const UPDATE_ADDRESS_FAILED = "UPDATE_ADDRESS_FAILED";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESSFUL = "DELETE_ADDRESS_SUCCESSFUL";
export const DELETE_ADDRESS_FAILED = "DELETE_ADDRESS_FAILED";

export const TRACK_ORDER_REQUEST = "TRACK_ORDER_REQUEST";
export const TRACK_ORDER_SUCCESSFUL = "TRACK_ORDER_SUCCESSFUL";
export const TRACK_ORDER_FAILED = "TRACK_ORDER_FAILED";

export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_SUCCESSFUL = "GET_OFFERS_SUCCESSFUL";
export const GET_OFFERS_FAILED = "GET_OFFERS_FAILED";
